name: Check burner-libs

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
    branches:
      - master

jobs:
  check_js_libs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --production=false
      - name: Run tsc (libburner-common)
        run: |
          cd packages/libburner-common
          yarn tsc
      - name: Run tsc (libburner)
        run: |
          cd packages/libburner
          yarn tsc
