name: Release libburner

on:
  push:
    tags:
      - 'libburner-v*'

jobs:
  release_main_lib:
    environment: production
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Enable corepack
        run: |
          export COREPACK_ENABLE_DOWNLOAD_PROMPT=0
          corepack enable
          yarn -v
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Run tsc (libburner-common)
        run: |
          cd packages/libburner-common
          yarn tsc
      - name: Run tsc (libburner)
        run: |
          cd packages/libburner
          yarn tsc
      - name: Publish package to npmjs
        run: cd packages/libburner && yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE_NPM_TOKEN }}
